# translation of pl.po to Polish
# Piotr Drąg <piotrdrag@gmail.com>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: pl\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-06-30 12:06-0400\n"
"PO-Revision-Date: 2010-06-21 09:22+0200\n"
"Last-Translator: Piotr Drąg <piotrdrag@gmail.com>\n"
"Language-Team: Polish <trans-pl@lists.fedoraproject.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: python/bin/report:91
msgid "Needs a filename."
msgstr "Wymaga nazwy pliku."

#: python/bin/report:93
msgid "Please specify only 1 filename."
msgstr "Proszę podać tylko jedną nazwę pliku."

#: python/bin/report:97
#, python-format
msgid "File %s does not exist."
msgstr "Plik %s nie istnieje."

#: python/bin/report:100
msgid "--gtk option specified, but report.io.GTKIO package not found."
msgstr "Podano opcję --gtk, ale nie odnaleziono pakietu report.io.GTKIO."

#: python/report/__init__.py:234 python/report/__init__.py:244
#: python/report/__init__.py:252 python/report/__init__.py:261
#: python/report/__init__.py:268 python/report/__init__.py:275
#: python/report/__init__.py:302 python/report/__init__.py:311
#: python/report/__init__.py:327 python/report/__init__.py:335
#: python/report/__init__.py:342 python/report/__init__.py:354
#: python/report/__init__.py:365
msgid "Signature File Format Error"
msgstr "Błąd formatu pliku podpisu"

#: python/report/__init__.py:235
#, python-format
msgid "file %s is a tarfile that does not contain a member named 'context.xml'"
msgstr ""
"plik %s jest plikiem tar, który nie zawiera elementu o nazwie \"context.xml\""

#: python/report/__init__.py:245
#, python-format
msgid "Failed to open file %(filename)s: %(error)s"
msgstr "Otarcie pliku %(filename)s nie powiodło się: %(error)s"

#: python/report/__init__.py:253
#, python-format
msgid "Failed to open file %s"
msgstr "Otarcie pliku %s nie powiodło się"

#: python/report/__init__.py:262
#, python-format
msgid "Error while parseing: %(filename)s: %(error)s"
msgstr "Błąd podczas przetwarzania: %(filename)s: %(error)s"

#: python/report/__init__.py:269
#, python-format
msgid "Could not parse XML file %s"
msgstr "Nie można przetworzyć pliku XML %s"

#: python/report/__init__.py:276
#, python-format
msgid "file %(filename)s has document tag that is not valid: %(signature)s"
msgstr ""
"plik %(filename)s posiada nieprawidłowy znacznik dokumentu: %(signature)s"

#: python/report/__init__.py:303
#, python-format
msgid ""
"file %(filename)s has document element that has children with an invalid "
"tag: %(tag)s"
msgstr ""
"plik %(filename)s posiada element dokumentu, który posiada potomków z "
"nieprawidłowymi znacznikami: %(tag)s"

#: python/report/__init__.py:312
#, python-format
msgid "file %s has binding element that has no 'name' attribute"
msgstr ""
"plik %s posiada element dowiązania, który nie posiada atrybutu \"name\""

#: python/report/__init__.py:328
#, python-format
msgid "file %s has a binding with an 'href' but no content"
msgstr "plik %s posiada dowiązanie z \"href\", ale bez zawartości"

#: python/report/__init__.py:336 python/report/__init__.py:343
#, python-format
msgid ""
"file %(filename)s is a tarfile that does not contain a member named '%"
"(member)s'"
msgstr ""
"plik %(filename)s jest plikiem tar, który nie zawiera elementu o nazwie \"%"
"(member)s\""

#: python/report/__init__.py:355
#, python-format
msgid ""
"file %(filename)s has a binding, %(binding)s, that has both a 'value' "
"attribute, and a text child"
msgstr ""
"plik %(filename)s posiada dowiązanie, %(binding)s, które posiada zarówno "
"atrybut \"value\", jak i potomka tekstowego"

#: python/report/__init__.py:366
#, python-format
msgid ""
"file %(filename)s has a binding, %(binding)s, that has neither a 'value' "
"attribute, or a text child"
msgstr ""
"plik %(filename)s posiada dowiązanie, %(binding)s, które nie posiada ani "
"atrybutu \"value\", ani potomka tekstowego"

#: python/report/__init__.py:458
msgid "No Such Plugin"
msgstr "Nie ma takiej wtyczki"

#: python/report/__init__.py:459
#, python-format
msgid "No plugin matching the requested: %s."
msgstr "Brak wtyczki pasującej do żądanej: %s."

#: python/report/__init__.py:463
msgid "Where do you want to send this report:"
msgstr "Gdzie wysłać ten raport:"

#: python/report/__init__.py:467
msgid "No Plugins"
msgstr "Brak wtyczek"

#: python/report/__init__.py:468
msgid "No usable plugins."
msgstr "Brak używalnych wtyczek."

#: python/report/__init__.py:473
msgid "No IO specified."
msgstr "Nie podano wejścia/wyjścia."

#: python/report/__init__.py:474
msgid "Cannot determine IO."
msgstr "Nie można określić wejścia/wyjścia."

#: python/report/plugins/scp/__init__.py:45
#: python/report/plugins/strata/__init__.py:61
#: python/report/plugins/localsave/__init__.py:43
#: python/report/plugins/ftp/__init__.py:44
#: python/report/plugins/bugzilla/__init__.py:64
msgid "No IO"
msgstr "Brak wejścia/wyjścia"

#: python/report/plugins/scp/__init__.py:46
#: python/report/plugins/strata/__init__.py:62
#: python/report/plugins/localsave/__init__.py:44
#: python/report/plugins/ftp/__init__.py:45
#: python/report/plugins/bugzilla/__init__.py:65
msgid "No io provided."
msgstr "Nie dostarczono wejścia/wyjścia."

#: python/report/plugins/scp/__init__.py:94
msgid "No Host"
msgstr "Brak komputera"

#: python/report/plugins/scp/__init__.py:95
msgid "Please provide a valid hostname"
msgstr "Proszę dostarczyć prawidłową nazwę komputera"

#: python/report/plugins/scp/__init__.py:118
msgid "Login Input Failed"
msgstr "Wprowadzenie loginu nie powiodło się"

#: python/report/plugins/scp/__init__.py:119
msgid "Please provide a valid username and password"
msgstr "Proszę dostarczyć prawidłową nazwę użytkownika i hasło"

#: python/report/plugins/scp/__init__.py:129
msgid "No Path"
msgstr "Brak ścieżki"

#: python/report/plugins/scp/__init__.py:130
msgid "Please provide a path"
msgstr "Proszę dostarczyć ścieżkę"

#: python/report/plugins/scp/__init__.py:151
#: python/report/plugins/scp/__init__.py:165
msgid "scp failed"
msgstr "scp nie powiodło się"

#: python/report/plugins/scp/__init__.py:152
#, python-format
msgid "OSError during scp file from %(filename)s to %(target)s: %(error)s"
msgstr ""
"Błąd systemu operacyjnego podczas kopiowania pliku za pomocą scp z %"
"(filename)s do %(target)s: %(error)s"

#: python/report/plugins/scp/__init__.py:160
msgid "scp Successful"
msgstr "scp powiodło się"

#: python/report/plugins/scp/__init__.py:161
#: python/report/plugins/localsave/__init__.py:107
msgid "The signature was successfully copied to:"
msgstr "Podpis został pomyślnie skopiowany do:"

#: python/report/plugins/scp/__init__.py:166
#, python-format
msgid ""
"unexpected child status (%(childstatus)s) during scp\n"
"scp %(filename)s %(target)s\n"
"%(childoutput)s"
msgstr ""
"nieoczekiwany stan potomka (%(childstatus)s) podczas wykonywania polecenia "
"scp\n"
"scp %(filename)s %(target)s\n"
"%(childoutput)s"

#: python/report/plugins/strata/__init__.py:106
#: python/report/plugins/bugzilla/__init__.py:235
msgid "Create Case"
msgstr "Utwórz przypadek"

#: python/report/plugins/strata/__init__.py:106
#: python/report/plugins/bugzilla/__init__.py:236
msgid "Create a Case"
msgstr "Utwórz przypadek"

#: python/report/plugins/strata/__init__.py:107
#: python/report/plugins/bugzilla/__init__.py:238
#: python/report/plugins/bugzilla/__init__.py:239
msgid "Attach to existing case"
msgstr "Dołącz do istniejącego przypadku"

#: python/report/plugins/strata/__init__.py:110
#: python/report/plugins/bugzilla/__init__.py:244
msgid "Create new case or Attach report to existing case?"
msgstr "Utworzyć nowy przypadek czy dołączyć do istniejącego?"

#: python/report/plugins/strata/__init__.py:124
msgid "Missing Login Information"
msgstr "Brak informacji logowania"

#: python/report/plugins/strata/__init__.py:125
#: python/report/plugins/bugzilla/__init__.py:172
msgid "Please provide a valid username and password."
msgstr "Proszę podać prawidłową nazwę użytkownika i hasło."

#: python/report/plugins/strata/__init__.py:149
msgid "Case Creation Failed"
msgstr "Utworzenie przypadku nie powiodło się"

#: python/report/plugins/strata/__init__.py:152
msgid "Case Creation Response"
msgstr "Odpowiedź utworzenia przypadku"

#: python/report/plugins/strata/__init__.py:153
#, fuzzy
msgid "Case Creation Succeeded"
msgstr "Utworzenie przypadku powiodło się"

#: python/report/plugins/strata/__init__.py:172
msgid "Report Attachement Failed"
msgstr "Załączenie raportu nie powiodło się"

#: python/report/plugins/strata/__init__.py:175
msgid "Report Attachment Response"
msgstr "Odpowiedź załączenia raportu"

#: python/report/plugins/strata/__init__.py:176
msgid "Report Attachment Succeded"
msgstr "Załączenie raportu powiodło się"

#: python/report/plugins/localsave/__init__.py:63
msgid "directory to store report in"
msgstr "katalog, w którym przechować raport"

#: python/report/plugins/localsave/__init__.py:67
#: python/report/plugins/localsave/__init__.py:74
#: python/report/plugins/localsave/__init__.py:92
#: python/report/plugins/localsave/__init__.py:102
msgid "local save Failed"
msgstr "zapisanie lokalnego pliku nie powiodło się"

#: python/report/plugins/localsave/__init__.py:68
msgid "directory name required"
msgstr "wymagana jest nazwa katalogu"

#: python/report/plugins/localsave/__init__.py:75
#, python-format
msgid "'%s' already exists, but is not a directory"
msgstr "\"%s\" już istnieje, ale nie jest katalogiem"

#: python/report/plugins/localsave/__init__.py:78
#, python-format
msgid "'%s' does not exist, create it?"
msgstr "\"%s\" nie istnieje, utworzyć?"

#: python/report/plugins/localsave/__init__.py:79
msgid "OK"
msgstr "OK"

#: python/report/plugins/localsave/__init__.py:80
msgid "Create the directory"
msgstr "Utwórz katalog"

#: python/report/plugins/localsave/__init__.py:82
msgid "Cancel"
msgstr "Anuluj"

#: python/report/plugins/localsave/__init__.py:83
msgid "Cancel the local save"
msgstr "Anuluj lokalny zapis"

#: python/report/plugins/localsave/__init__.py:93
#, python-format
msgid "could not create '%(dir)s': %(error)s"
msgstr "nie można utworzyć \"%(dir)s\": %(error)s"

#: python/report/plugins/localsave/__init__.py:103
#, python-format
msgid "could not save report to '%(target)s': %(error)s"
msgstr "nie można zapisać raportu do \"%(target)s\": %(error)s"

#: python/report/plugins/localsave/__init__.py:106
msgid "local save Successful"
msgstr "lokalny zapis powiódł się"

#: python/report/plugins/ftp/__init__.py:67
msgid "Enter remote FTP directory as URL"
msgstr "Proszę podać zdalny katalog FTP jako adres URL"

#: python/report/plugins/ftp/__init__.py:99
msgid "Upload failed"
msgstr "Wysłanie nie powiodło się"

#: python/report/plugins/ftp/__init__.py:100
#, python-format
msgid "Upload has failed for remote path: %(ftpserver)s, %(error)s"
msgstr "Wysłanie do zdalnej ścieżki nie powiodło się: %(ftpserver)s, %(error)s"

#: python/report/plugins/ftp/__init__.py:103
msgid "Upload Successful"
msgstr "Wysłanie powiodło się"

#: python/report/plugins/ftp/__init__.py:104
msgid "The signature was successfully uploaded to:"
msgstr "Pomyślnie wysłano podpis do:"

#: python/report/plugins/bugzilla/__init__.py:128
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"Nie można zgłosić błędu z powodu następującego błędu podczas komunikowania "
"się z Bugzillą:\n"
"\n"
"%s"

#: python/report/plugins/bugzilla/__init__.py:130
#: python/report/plugins/bugzilla/__init__.py:137
msgid "Unable To File Bug"
msgstr "Nie można zgłosić błędu"

#: python/report/plugins/bugzilla/__init__.py:134
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"Nie można zgłosić błędu z powodu błędnych informacji w polach błędu. Jest to "
"prawdopodobnie błąd w programie do zgłaszania błędów:\n"
"\n"
"%s"

#: python/report/plugins/bugzilla/__init__.py:157
msgid "Bug Filing Not Supported"
msgstr "Zgłaszanie błędów nie jest obsługiwane"

#: python/report/plugins/bugzilla/__init__.py:158
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"Dystrybucja nie dostarcza obsługiwanego systemu zgłaszania błędów, więc nie "
"można zapisać wyjątku w ten sposób."

#: python/report/plugins/bugzilla/__init__.py:171
msgid "No Login Information"
msgstr "Brak informacji logowania"

#: python/report/plugins/bugzilla/__init__.py:179
msgid "Unable To Login"
msgstr "Nie można się zalogować"

#: python/report/plugins/bugzilla/__init__.py:180
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr ""
"Wystąpił błąd podczas logowania do %s używając podanej nazwy użytkownika i "
"hasła."

#: python/report/plugins/bugzilla/__init__.py:206
#: python/report/plugins/bugzilla/__init__.py:282
msgid "Bug not found"
msgstr "Nie odnaleziono błędu"

#: python/report/plugins/bugzilla/__init__.py:207
#: python/report/plugins/bugzilla/__init__.py:283
#, python-format
msgid "Unable to find bug %s"
msgstr "Nie można odnaleźć błędu %s"

#: python/report/plugins/bugzilla/__init__.py:331
msgid "Bug Created"
msgstr "Utworzono błąd"

#: python/report/plugins/bugzilla/__init__.py:332
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:"
msgstr ""
"Utworzono nowy błąd z dołączonym wyjątkiem. Proszę dodać informacje (w "
"języku angielskim), takie jak wykonywana czynność podczas wystąpienia błędu, "
"zrzuty ekranu, i wszystko co jest odpowiednie do poniższego błędu:"

#: python/report/plugins/bugzilla/__init__.py:359
msgid "Bug Updated"
msgstr "Zaktualizowano błąd"

#: python/report/plugins/bugzilla/__init__.py:360
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:"
msgstr ""
"Błąd zawierający te informacje już istnieje. Konto zostało dodane do listy "
"CC, a wyjątek dodany jako komentarz. Proszę dodać inne informacje do "
"poniższego błędu:"
